name: Deploy to Dev.

on:
  push:
    branches:
      - main

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_VERSION: dev-${{github.sha}}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Package With Maven
        run: |
          mvn clean package -DskipTests
      - name: Build docker image
        run: |
          docker build -f Dockerfile -t kyosk/interview-demo:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Tag docker image
        run: |
          docker tag kyosk/interview-demo:latest kyoskinterview/interview-demo:latest
      - name: Push to registry
        run: |
          docker push kyoskinterview/interview-demo:latest
