name: Deploy to Dev.

on:
  push:
    branches:
      - dev

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest  # picks the OS to run with
    env:
      GH_VERSION: dev-${{github.sha}} # used for versioning especially when expecting many pushes the github sha makes the version unique according to the commit sha
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17 # setsup java 17
      - name: Package With Maven # Packages the project to create a runnable jar file.
        run: |
          mvn clean package -DskipTests
      - name: Build docker image # The docker image is bilt and tagged over
        run: |
          docker build -f Dockerfile -t kyosk/interview-demo:latest .
      - name: Login to Docker Hub # This step logs in to the docker hub acc whose credentials are stored in the secrets on github for safe keeping
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Tag docker image # tag and push the image to docker hub.
        run: |
          docker tag kyosk/interview-demo:latest kyoskinterview/interview-demo:latest
      - name: Push to registry
        run: |
          docker push kyoskinterview/interview-demo:latest